<a href="https://colab.research.google.com/github/Mamtajangra/pytorch_tensor_autograd_practice/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("/content/Breast_cancer_dataset.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [3]:
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.tail(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424         M        21.56         22.39          142.00     1479.0   
565  926682         M        20.13         28.25          131.20     1261.0   
566  926954         M        16.60         28.08          108.30      858.1   
567  927241         M        20.60         29.33          140.10     1265.0   
568   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
564                  0.07115          NaN  
565                  0.06637          NaN  
566                  0.07820          NaN  
567                  0.12400          NaN  
568                  0.07039          NaN  

[5 rows x 33 columns]

In [5]:
df.sample(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  \
237     883263         M        20.48         21.46          132.50   
396   90401601         B        13.51         18.89           88.10   
517     916838         M        19.89         20.26          130.50   
461  911296202         M        27.42         26.27          186.90   
286    8912909         B        11.94         20.76           77.87   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
237     1306.0          0.08355           0.08348         0.09042   
396      558.1          0.10590           0.11470         0.08580   
517     1214.0          0.10370           0.13100         0.14110   
461     2501.0          0.10840           0.19880         0.36350   
286      441.0          0.08605           0.10110         0.06574   

     concave points_mean  ...  texture_worst  perimeter_worst  area_worst  \
237              0.06022  ...          26.17           161.70      1750.0   
396              0.05381  ...          27.20            97.33       675.2   
517              0.09431  ...          25.23           160.50      1646.0   
461              0.16890  ...          31.37           251.20      4254.0   
286              0.03791  ...          27.29            92.20       546.1   

     smoothness_worst  compactness_worst  concavity_worst  \
237            0.1228             0.2311           0.3158   
396            0.1428             0.2570           0.3438   
517            0.1417             0.3309           0.4185   
461            0.1357             0.4256           0.6833   
286            0.1116             0.2813           0.2365   

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
237                0.1445          0.2238                  0.07127   
396                0.1453          0.2666                  0.07686   
517                0.1613          0.2549                  0.09136   
461                0.2625          0.2641                  0.07427   
286                0.1155          0.2465                  0.09981   

     Unnamed: 32  
237          NaN  
396          NaN  
517          NaN  
461          NaN  
286          NaN  

[5 rows x 33 columns]

In [6]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [45]:
df.drop(columns =["id","Unnamed: 32"],inplace = True)

In [46]:
X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

In [47]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [48]:
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

In [49]:
X_train

array([[ 0.12192762, -0.56492251,  0.06808903, ..., -0.56740866,
        -0.7402027 , -1.00819558],
       [-1.06803202, -0.16071781, -1.06612813, ..., -0.76456061,
        -1.13066025, -0.29755199],
       [ 1.17425337, -0.16760766,  1.07955362, ...,  0.62793874,
         0.47150648, -0.81313931],
       ...,
       [ 2.8774727 ,  0.2044444 ,  3.05354765, ...,  1.65464541,
         0.49732186, -0.20230522],
       [-1.28881971, -0.25028589, -1.32034206, ..., -1.75456668,
        -1.62115239, -1.02929815],
       [-0.65513036, -1.92911338, -0.68128223, ..., -0.71178455,
        -0.73213539, -0.62834917]])

In [50]:
X_test

array([[-1.19419642e+00, -4.08752511e-01, -1.16773076e+00, ...,
        -7.68958614e-01, -3.18933361e-02, -3.99072506e-01],
       [-6.73189770e-02,  7.12405742e-02, -6.00546988e-02, ...,
         1.01617642e+00,  4.27943039e-01,  1.24692860e+00],
       [ 1.87877186e-01,  2.06741015e-01,  1.47297615e-01, ...,
        -2.12231852e-01, -8.78960342e-01, -1.00648456e+00],
       ...,
       [-6.66599854e-01, -2.20429865e-01, -6.32347086e-01, ...,
        -2.87288881e-02,  7.79677529e-01,  7.35801214e-04],
       [-5.37568087e-01, -1.00127986e+00, -5.92120737e-01, ...,
        -1.02768263e+00, -9.93516071e-01, -1.36294703e+00],
       [-4.23677937e-03,  2.80232779e-01, -6.55780176e-03, ...,
         2.76098350e-01, -6.12739283e-01, -2.88426555e-01]])

In [51]:
y_train

486    B
303    B
186    M
39     M
201    M
      ..
436    B
440    B
122    M
192    B
401    B
Name: diagnosis, Length: 455, dtype: object

In [52]:
y_test

338    B
435    M
495    B
536    M
252    M
      ..
210    M
370    M
216    B
404    B
476    B
Name: diagnosis, Length: 114, dtype: object

In [53]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [54]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [55]:
y_test

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0])

# now convert numpy array to **tensors**

In [56]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [57]:
X_train_tensor

tensor([[ 0.1219, -0.5649,  0.0681,  ..., -0.5674, -0.7402, -1.0082],
        [-1.0680, -0.1607, -1.0661,  ..., -0.7646, -1.1307, -0.2976],
        [ 1.1743, -0.1676,  1.0796,  ...,  0.6279,  0.4715, -0.8131],
        ...,
        [ 2.8775,  0.2044,  3.0535,  ...,  1.6546,  0.4973, -0.2023],
        [-1.2888, -0.2503, -1.3203,  ..., -1.7546, -1.6212, -1.0293],
        [-0.6551, -1.9291, -0.6813,  ..., -0.7118, -0.7321, -0.6283]],
       dtype=torch.float64)

In [58]:
X_test_tensor

tensor([[-1.1942e+00, -4.0875e-01, -1.1677e+00,  ..., -7.6896e-01,
         -3.1893e-02, -3.9907e-01],
        [-6.7319e-02,  7.1241e-02, -6.0055e-02,  ...,  1.0162e+00,
          4.2794e-01,  1.2469e+00],
        [ 1.8788e-01,  2.0674e-01,  1.4730e-01,  ..., -2.1223e-01,
         -8.7896e-01, -1.0065e+00],
        ...,
        [-6.6660e-01, -2.2043e-01, -6.3235e-01,  ..., -2.8729e-02,
          7.7968e-01,  7.3580e-04],
        [-5.3757e-01, -1.0013e+00, -5.9212e-01,  ..., -1.0277e+00,
         -9.9352e-01, -1.3629e+00],
        [-4.2368e-03,  2.8023e-01, -6.5578e-03,  ...,  2.7610e-01,
         -6.1274e-01, -2.8843e-01]], dtype=torch.float64)

In [59]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [60]:
y_test

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0])

In [61]:
X_train_tensor.shape

torch.Size([455, 30])

In [62]:
y_train_tensor.shape

torch.Size([455])

In [63]:
X_test_tensor.shape

torch.Size([114, 30])

In [64]:
y_test_tensor.shape

torch.Size([114])

In [71]:
## we created class here because we want to store all function at one place
# 1.to determine weight and bias
# 2.forward pass= z = w*x+b and sigmoid
# 3.


class MySimpleNN():        ###

  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype = torch.float64,requires_grad = True)
    self.bias = torch.rand(1,dtype = torch.float64,requires_grad = True)

# forward pass
  def forward_pass(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


    ## loss_function
# Agar output 0/1, ya Yes/No, ya class labels ho → Entropy-based loss
# Agar output real number ho (jaise weight, price, temperature) → MSE
# Breast Cancer dataset = 0 or 1
# → so “entropy (cross entropy / BCE)” automatically correct choice.
  def loss_function(self,y_pred,y):
     # Clamp predictions to avoid log(0)
    epsilon = 1e-7     ## ek chota sa number set kiya jo zero ke bahut paas hai
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # torch.clamp(y_pred, epsilon, 1 - epsilon)
    # agar y_pred 0 tha → 0.0000001 bana diya
    # agar y_pred 1 tha → 0.9999999 bana diya
    # Taaki log(0) ya division-by-zero error na aaye


    # Calculate loss
# formula of loss    # loss = -(y * log(y_pred) + (1 - y) * log(1 - y_pred)).mean()

    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [ ]:
print(X_train_tensor.dtype)
print(y_train_tensor.dtype)
print(model.weights.dtype)
print(model.bias.dtype)

In [80]:
learning_rate = 0.1
epochs = 25

In [81]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward_pass(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')



Epoch: 1, Loss: 3.274786211656471
Epoch: 2, Loss: 3.143800830779312
Epoch: 3, Loss: 3.0112333308898602
Epoch: 4, Loss: 2.8749039466586392
Epoch: 5, Loss: 2.7390090978452646
Epoch: 6, Loss: 2.5988890759093515
Epoch: 7, Loss: 2.457458878055127
Epoch: 8, Loss: 2.312380871357608
Epoch: 9, Loss: 2.1664719834302497
Epoch: 10, Loss: 2.02180314045911
Epoch: 11, Loss: 1.8773541092798611
Epoch: 12, Loss: 1.735251473059453
Epoch: 13, Loss: 1.6013338841800477
Epoch: 14, Loss: 1.476859165893018
Epoch: 15, Loss: 1.361371870782493
Epoch: 16, Loss: 1.257402288609428
Epoch: 17, Loss: 1.1678748348881713
Epoch: 18, Loss: 1.0925296829958828
Epoch: 19, Loss: 1.030465752968504
Epoch: 20, Loss: 0.9802792922328147
Epoch: 21, Loss: 0.9402409622857132
Epoch: 22, Loss: 0.9084687709214024
Epoch: 23, Loss: 0.8831201125452062
Epoch: 24, Loss: 0.8625879883041951
Epoch: 25, Loss: 0.8456170131923995


In [84]:
model.bias

tensor([0.1732], dtype=torch.float64, requires_grad=True)

# *evaluation*

In [86]:
# there is no need to determine the previous gradient so we will disable this
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  # Comparison: y_pred > 0.9
  # Agar model ne 0.95 predict kiya → True
  # Agar 0.30 predict kiya → False

  accuracy = (y_pred == y_test_tensor).float().mean()
  #(y_pred == y_test_tensor) → Compares each prediction with actual label
  # predicted: 1 0 1 0
 # actual:    1 1 1 0
 # result:    T F T T
 # .mean() → average
 # Agar 4 me se 3 sahi tha:
 # (1+0+1+1)/4 = 0.75 → accuracy = 75%

  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6440443396568298
