<a href="https://colab.research.google.com/github/Mamtajangra/pytorch_tensor_practice/blob/main/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU available")
  print(f"using gpu:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")



GPU is not available


# tensor type

In [ ]:
scalar = torch.tensor(4)
print(scalar)
print(scalar.shape)

tensor(4)
torch.Size([])


In [ ]:
vector = torch.tensor([1,2,3,4])
print(vector.shape)
vector.shape

torch.Size([4])


torch.Size([4])

In [ ]:
vector = torch.tensor([1, 2, 3])
print(vector.shape)

torch.Size([3])


In [ ]:
matrix = torch.tensor([[1,2],[4,5]])
print(matrix.shape)

torch.Size([2, 2])


In [ ]:
matrix = torch.tensor([[1, 2], [3, 4]])
print(matrix.shape)


torch.Size([2, 2])


In [ ]:
tensor3_d = torch.tensor([[[1,2,3],[4,5,6]],[[2,3,4],[6,5,4]]])
print(tensor3_d.shape)

torch.Size([2, 2, 3])


# tensor creation

In [ ]:
## tensor creation
a = torch.empty(2,4)
print(a)

tensor([[2.1715e-18, 2.3081e-12, 1.8590e+34, 7.7767e+31],
        [1.7181e+19, 1.8990e+28, 1.5766e-19, 2.1707e-18]])


In [ ]:
b = torch.zeros(2,4)
print(b)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
c = torch.ones(3,4)
print(c)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
torch.manual_seed(42)
d = torch.rand(2,3)
print(d)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
e = torch.arange(2,9,2)
print(e)

tensor([2, 4, 6, 8])


In [ ]:
f = torch.linspace(2,4,7)
print(f)

tensor([2.0000, 2.3333, 2.6667, 3.0000, 3.3333, 3.6667, 4.0000])


In [ ]:
g = torch.eye(5)
print(g)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
h = torch.full((4,4),5)
print(h)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [ ]:
## tensor shape
h.shape

torch.Size([4, 4])

In [ ]:
h.size

<function Tensor.size>

# create similar tensor

In [ ]:
i = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(i)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
print(torch.ones_like(i))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [ ]:
print(torch.zeros_like(i))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
print(torch.empty_like(i))

tensor([[      167972208, 137215406979296,               1],
        [              9,               0,               0],
        [              0,               0,               1]])


In [ ]:
j = torch.tensor([[1.2,2,3.6],[4.9,5.6,6],[7,8,9]])
print(j)


tensor([[1.2000, 2.0000, 3.6000],
        [4.9000, 5.6000, 6.0000],
        [7.0000, 8.0000, 9.0000]])


In [ ]:
print(torch.rand_like(j))          ## kyunki rand float value deta h so ye i jaisa nhi bna agar i mein float value hoti to ye bn jaata jaise j ke liye ho gya

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])


In [ ]:
# print(torch.rand_like(i))  ## iska solution hai ki dtype add krdo like
print(torch.rand_like(i,dtype = torch.float32))

tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])


# tensor datatype

In [ ]:
j.dtype

torch.float32

In [ ]:
i.dtype

torch.int64

In [ ]:
x = torch.tensor([1,2,3],dtype = torch.float32)
print(x)

tensor([1., 2., 3.])


In [ ]:
y = torch.tensor([1.3,2,3.9],dtype = torch.int32)
print(y)
y.to(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
x.to(torch.float32)     ## its another way

tensor([1., 2., 3.])

# mathematical operation

In [ ]:
x = torch.rand(3,3)
print(x)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860]])


In [ ]:
print(x+2)

tensor([[2.1053, 2.2695, 2.3588],
        [2.1994, 2.5472, 2.0062],
        [2.9516, 2.0753, 2.8860]])


In [ ]:
print(x-3)

tensor([[-2.8947, -2.7305, -2.6412],
        [-2.8006, -2.4528, -2.9938],
        [-2.0484, -2.9247, -2.1140]])


In [ ]:
print(x*4)

tensor([[0.4213, 1.0780, 1.4353],
        [0.7975, 2.1888, 0.0246],
        [3.8062, 0.3011, 3.5441]])


In [ ]:
print(x/3)

tensor([[0.0351, 0.0898, 0.1196],
        [0.0665, 0.1824, 0.0021],
        [0.3172, 0.0251, 0.2953]])


In [ ]:
print(x//3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
print(x%2)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860]])


In [ ]:
print(x**3)

tensor([[1.1681e-03, 1.9573e-02, 4.6196e-02],
        [7.9239e-03, 1.6384e-01, 2.3379e-07],
        [8.6159e-01, 4.2638e-04, 6.9554e-01]])


# elementwise operation

In [ ]:
a = torch.tensor([[2,3],[3,4]])
b = torch.tensor([[3,6],[4,5]])
print(a)
print(b)

tensor([[2, 3],
        [3, 4]])
tensor([[3, 6],
        [4, 5]])


In [ ]:
print(a+b)

tensor([[5, 9],
        [7, 9]])


In [ ]:
print(a-b)

tensor([[-1, -3],
        [-1, -1]])


In [ ]:
print(a*b)

tensor([[ 6, 18],
        [12, 20]])


In [ ]:
print(a/b)

tensor([[0.6667, 0.5000],
        [0.7500, 0.8000]])


In [ ]:
print(a//b)

tensor([[0, 0],
        [0, 0]])


In [ ]:
print(a%b)

tensor([[2, 3],
        [3, 4]])


In [ ]:
c = torch.abs(b)
print(c)

tensor([[3, 6],
        [4, 5]])


In [ ]:
print(torch.neg(c))

tensor([[-3, -6],
        [-4, -5]])


In [ ]:
d = torch.tensor([[2,3.1],[3.2,5]])

In [ ]:
print(torch.ceil(d))

tensor([[2., 4.],
        [4., 5.]])


In [ ]:
print(torch.floor(d))

tensor([[2., 3.],
        [3., 5.]])


In [ ]:
print(torch.round(d))

tensor([[2., 3.],
        [3., 5.]])


In [ ]:
print(torch.clamp(d,min =2,max =3))   ## ye uper wale tensor ko ek level pe le aayega 2 to 3

tensor([[2., 3.],
        [3., 3.]])


# reduction operation

In [ ]:
x = torch.randint(size = (2,3),low = 0,high = 8,dtype = torch.float32)
print(x)

tensor([[1., 5., 4.],
        [3., 0., 0.]])


In [ ]:
print(torch.sum(x))

tensor(13.)


In [ ]:
print(torch.sum(x,dim = 0)) ## sum towards row

tensor([4., 5., 4.])


In [ ]:
print(torch.sum(x,dim = 1))       ## sum towards columns

tensor([10.,  3.])


In [ ]:
print(torch.mean(x))  ## simple mean nhi niklega uske liye chahiye ki x main datatype ko float krdo

tensor(2.1667)


In [ ]:
print(torch.mean(x,dim= 0))

tensor([2.0000, 2.5000, 2.0000])


In [ ]:
print(torch.median(x))

tensor(1.)


In [ ]:
print(torch.std(x))

tensor(2.1370)


In [ ]:
print(torch.max(x))

tensor(5.)


In [ ]:
print(torch.min(x))

tensor(0.)


In [ ]:
print(torch.prod(x))

tensor(0.)


In [ ]:
print(torch.argmax(x))

tensor(1)


In [ ]:
print(torch.argmin(x))

tensor(4)


In [ ]:
print(torch.var(x))

tensor(4.5667)


# matrix operation

In [ ]:
x = torch.randint(size=(2,3),low = 3,high = 9)
y = torch.randint(size=(3,2),low = 4,high = 7)
print(x)
print(y)

tensor([[3, 5, 3],
        [4, 6, 6]])
tensor([[6, 6],
        [5, 4],
        [6, 4]])


In [ ]:
print(torch.matmul(x,y))

tensor([[61, 50],
        [90, 72]])


In [ ]:
a = torch.tensor([1,2])
b = torch.tensor([5,6])

In [ ]:
print(torch.dot(a,b))

tensor(17)


In [ ]:
c = torch.randint(size = (3,3),low = 3,high = 9,dtype = torch.float32)
print(c)

tensor([[6., 7., 6.],
        [7., 4., 4.],
        [5., 5., 3.]])


In [ ]:
print(torch.det(c))

tensor(35.0000)


In [ ]:
print(torch.inverse(c))

tensor([[-0.2286,  0.2571,  0.1143],
        [-0.0286, -0.3429,  0.5143],
        [ 0.4286,  0.1429, -0.7143]])


# comparison

In [ ]:
x = torch.randint(size=(2,3),low = 3,high = 9,dtype= torch.float32)
y = torch.randint(size=(2,3),low = 4,high = 7)
print(x)
print(y)

tensor([[5., 3., 5.],
        [7., 3., 8.]])
tensor([[4, 5, 5],
        [5, 6, 4]])


In [ ]:
print(x>y)

tensor([[ True, False, False],
        [ True, False,  True]])


In [ ]:
print(x>=y)

tensor([[ True, False,  True],
        [ True, False,  True]])


In [ ]:
print(x<y)

tensor([[False,  True, False],
        [False,  True, False]])


In [ ]:
print(x<=y)

tensor([[False,  True,  True],
        [False,  True, False]])


In [ ]:
print(x==y)

tensor([[False, False,  True],
        [False, False, False]])


In [ ]:
print(x!=y)

tensor([[ True,  True, False],
        [ True,  True,  True]])


# special function

In [ ]:
print(torch.log(x))

tensor([[1.6094, 1.0986, 1.6094],
        [1.9459, 1.0986, 2.0794]])


In [ ]:
print(torch.sqrt(x))

tensor([[2.2361, 1.7321, 2.2361],
        [2.6458, 1.7321, 2.8284]])


In [ ]:
print(torch.exp(x))

tensor([[ 148.4132,   20.0855,  148.4132],
        [1096.6332,   20.0855, 2980.9580]])


In [ ]:
print(torch.sigmoid(x))

tensor([[0.9933, 0.9526, 0.9933],
        [0.9991, 0.9526, 0.9997]])


In [ ]:
print(torch.softmax(x,dim = 0))

tensor([[0.1192, 0.5000, 0.0474],
        [0.8808, 0.5000, 0.9526]])


In [ ]:
print(torch.relu)

<built-in method relu of type object at 0x7cccdd6f74a0>


# inplace

In [ ]:
###
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.8035, 0.3813, 0.7860],
        [0.1115, 0.2477, 0.6524]])
tensor([[0.6057, 0.3725, 0.7980],
        [0.8399, 0.1374, 0.2331]])


In [ ]:
m+n   ## if i use m+n here means it create some space to memory to allocate that tensor but inplace help to avoid this means we will change m adding n to m so there is no need to allocate extra space

tensor([[1.4092, 0.7539, 1.5841],
        [0.9514, 0.3851, 0.8855]])

In [ ]:
m.add_(n)

tensor([[1.4092, 0.7539, 1.5841],
        [0.9514, 0.3851, 0.8855]])

# copying a tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
b = a

In [ ]:
a

tensor([[0.9578, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
b

tensor([[0.9578, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
a[0][0]  = 0

In [ ]:
a

tensor([[0.0000, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
b    ## meanshmne kiya ki assignment operator se copy to bna di a ki but jb a ka koi element change kiya same b ka bhi ho gya to ye problem hai iske liye dusra function hota hai jisko bolte hai clone

tensor([[0.0000, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
b = a.clone()

In [ ]:
b


tensor([[0.0000, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
a

tensor([[0.0000, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
b

tensor([[0.0000, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])

In [ ]:
id(a)

137215407193808

In [ ]:
id(b)

137215083130752

# tensor operation on gpu

In [ ]:
import torch

In [ ]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [ ]:
device = torch.device("cuda")

In [ ]:
a = torch.rand((2,3),device = device)

In [ ]:
b = torch.rand(3,2)

In [ ]:
a = b.to(device)
print(a)

tensor([[0.8961, 0.9272],
        [0.4554, 0.2741],
        [0.1097, 0.0328]], device='cuda:0')


# reshaping tensor

In [ ]:
x = torch.rand(3,5)
print(x)

In [ ]:
print(x.flatten())

In [ ]:
print(x.reshape(5,3))

In [ ]:
x.permute(1,0)       ## we will flip index number in permutation

In [ ]:
torch.rand(226,226,3)
y = x.unsqueeze(0)   ## yahan pe na 0th index pe  1   add ho jaayega

In [ ]:
y.squeeze(0)    ## jo 0 position pe hoga chla jaayega

# moving numpy to torch and vice versa

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
print(x)

In [ ]:
torch.from_numpy(x)

In [ ]:
y = torch.tensor([1,2,3])
print(y)

In [ ]:
z = y.numpy()
print(z)